apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: social-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:13 #
          env:
            - name: POSTGRES_USER
              value: "postgres_user"
            - name: POSTGRES_PASSWORD
              value: "postgres_password"
            - name: POSTGRES_DB
              value: "mydb"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-storage
          persistentVolumeClaim:
            claimName: postgresql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: social-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: social-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: postgresql
  clusterIP: None # This will expose the service within the cluster (headless service)